### PR TITLE
fix(evil): evil repeat error

### PR DESCRIPTION
**Pull request by donneyluck**
fix evil repeat error

### CODE REVIEW

**Comment by abougouffa** [comment]
Cannot reproduce the bug on my machine! Pressing '.' doesn't cause any issue in my case.

**Comment by donneyluck** [comment]
ok i will test again

**Comment by donneyluck** [comment]
I'm sorry to reply to the child so late, the child is sick again
Here's how to reproduce it
1. select line or region
2. press shift + >  then  selected region  move to right
3. press .   call evil-repeat to move again will     then Report an error

**Comment by donneyluck** [comment]
After 0 kbd macro iterations: evil-motion-range: Wrong type argument: commandp, ((keymap (intercept-state . operator) "Auxiliary keymap for Operator-Pending state") (keymap (62 . evil-line-or-visual-line)) (keymap) (keymap "Auxiliary keymap for Operator-Pending state" (88 . evil-snipe-X) (120 . evil-snipe-x) (90 . evil-snipe-S) (122 . evil-snipe-s)) (keymap "Auxiliary keymap for Operator-Pending state" (83 . evil-Surround-edit) (115 . evil-surround-edit)) (keymap (105 keymap (111 . evil-inner-symbol) (116 . evil-inner-tag) (96 . evil-inner-back-quote) (34 . evil-inner-double-quote) (39 . evil-inner-single-quote) (62 . evil-inner-angle) (60 . evil-inner-angle) (125 . evil-inner-curly) ...) (97 keymap (111 . evil-a-symbol) (116 . evil-a-tag) (96 . evil-a-back-quote) (34 . evil-a-double-quote) (39 . evil-a-single-quote) (62 . evil-an-angle) (60 . evil-an-angle) (125 . evil-a-curly) ...)) (keymap (intercept-state . motion) "Auxiliary keymap for Motion state") (keymap) (keymap (86 . evil-visual-screen-line) (36 . evil-end-of-visual-line) (48 . evil-beginning-of-visual-line) (107 . evil-previous-visual-line) (103 keymap (36 . evil-end-of-line) (48 . evil-beginning-of-line) (107 . evil-previous-line) (106 . evil-next-line)) (106 . evil-next-visual-line) "Minor-mode keymap for visual-line-mode in Motion state") (keymap "Auxiliary keymap for Motion state" (93 keymap (54 . evil-collection-unimpaired-b64-decode) (117 . evil-collection-unimpaired-url-decode)) (91 keymap (54 . evil-collection-unimpaired-b64-encode) (117 . evil-collection-unimpaired-url-encode))) ...)

**Comment by abougouffa** [comment]
@donneyluck 

How can I reproduce the problem? What are the steps.

What OS and Emacs version you are using?

**Comment by abougouffa** [comment]
Merged! I will test it further to see if there is a difference.
Thanks for the PR.

**Pull request merged**
